from ark_sdk_python.models.services.cmgr.ark_cmgr_list_pool_identifiers import ArkCmgrListPoolIdentifiers
from ark_sdk_python.models.services.cmgr.ark_cmgr_pools_common_filter import ArkCmgrPoolsCommonFilter


class ArkCmgrPoolIdentifiersFilter(ArkCmgrListPoolIdentifiers, ArkCmgrPoolsCommonFilter):
    pass
